# This file has been automatically generated by the wbfbd tool.
# Do not edit it manually, unless you really know what you do.
# https://github.com/Functional-Bus-Description-Language/PyWbFBD

BUS_WIDTH = {Bus Width}

class StatusSingleSingle:
    def __init__(self, interface, addr, mask):
        self.interface = interface
        self.addr = addr
        self.mask = ((1 << (mask[0] + 1)) - 1) ^ ((1 << mask[1]) - 1)
        self.shift = mask[1]

    def read(self):
        return (self.interface.read(self.addr) & self.mask) >> self.shift


class StatusArraySingle:
    def __init__(self, interface, addr, mask, count):
        self.interface = interface
        self.addr = addr
        self.mask = ((1 << (mask[0] + 1)) - 1) ^ ((1 << mask[1]) - 1)
        self.shift = mask[1]
        self.count = count

    def read(self, idx=None):
        if idx is None:
            idx = tuple(range(0, self.count))
        elif type(idx) == int:
            assert 0 <= idx < self.count
            return (self.interface.read(self.addr + idx) & self.mask) >> self.shift
        elif type(idx) == list or type(idx) == tuple:
            for i in idx:
                assert 0 <= i < self.count

        return [(self.interface.read(self.addr + i) & self.mask) >> self.shift for i in idx]


{Code}
